language: node_js
node_js:
  - node
email:
  on_failure: change
  on_success: never
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: "x64hU5V8mVENWiOE8UjTApTyQiKSO32ay95fn2oj2TojMhumFmOtJ/5aZtzCBUTYbiBNi7MmSuHyN+cBzVoXPaIRv/84+3oJmypkK9D0B9S5y41sFBwk2Rb0bHcubwvyTUSZA2uTFRA8P/FoUfz5xRww7UojtHCuD26hz0+eqp8I31P/2dutPD2NPy16klsWpbYcnj8Y6c0cLR6L/eHk+e6CFeXg32zr5+QeoVfLAsPVQaqowjKl22t8V7bS4Nj+NzU1wYp9fbF6OFroWofx45SGBSi7Nbl6IncS1y2PD54mkqIO+B+VjY2ehO0BmAh5P1mK4pHmG8puBC+mYcL/hLvyBjftsv6LrVHjJzv40kdLli5dDZYIIZAyIAo8lO7EhbX1A6YaOu5BU3go5SNproIkR/+IhJwoCzMjyzXKNKprHsTSjZ7Nlx8XEgI0P9UgMpsixoavqjHFqj2viapRHZa5/C3yk7B8OpIIFImPH0mG/QthhL14qtEXIHuXkT9+IaLaWQB6vJtfFi2GI0FRswob0EMBMdr4yaPcybxxm21LgLYffa7WFHai/X59ks5073XSy+Dg4JDMk1gDSBRI8HIDUeFIwlWLb2bwW06fo4A4EBe2VkNtnc3qfjL8aIRSfSfMjbPN3uhmmQIlI6kDwv1Z51cshUOVYHSCQUf1Whc="
  api_key:
    secure: "TIc1RHwQKlUxaXUoHDTX6vodCZ0qRbCdlBU8Z305Ot5RV79W4g5xrTfubqf5AnA40wRbXKPLctnmHhi+ArbdFfZ4Cz6W43YdqYfeo+jmdkfvnSV5N1qTuw3YoxWGwMUKK00kBmO/z6U70aV+T8H8gwZHV0EgaAEFPxVlxHG1dP0S/7BKuzgLVQpnyLhe5Lw/DTEvFTKEnxUuTl15Ja47OJD9vitNm61MfSgkz83x1i0B9lISG9lfAf4/D+obcVNRKQCSuyWB2Z7f9BvE3hXSuR82XllPdMRsn37wKRqUJLgf3nz/fgHtuGgnpllC7sx9wT951oTXUeJC5JDcm7q0sTZIgpb15Q9muxbdJCjMVGsh7oEjOJw6lYpXYzAb2hMyIBEfT4ngrMfkPM5ThAqiFzQjotVjph7cPozFv0Kfq2Rjw4I//F48jScSuH2uC5wTXoJv8mWF9EWkzbyiGEhR92ZxT1GntLScYB3Fx4qTGA+rmuqi9RFdCFFtTYOaYvS/RB4pmRuLIJs776a/r0Xmg7LJup1KSVJhlK9PfJJt7Faqis7p0CehvZXb/xOhN8YcJIETr0AGccMobQtnBjZ5b0UySEgT1RVwXsUcxIKUKxKENlvy+3VT1MBih4Ey6M/BRDjJm+Bk+U19CWLkoJyyERShWnw3Vs71uyoEJtn643w="
  on:
    branch: master
    repo: groundbreaker/qewl
