language: node_js
node_js:
  - node
email:
  on_failure: change
  on_success: never
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: OZyzFWTax3R5wreeFhGBDKKFgEttEusFEyLPWGcE3r3VLPbgru6X9UrYfFXOZFv+XLqCs8DqArYiXBuCsqfW7COSGukeyrcJ8tA2EQe5c2HpI7ObMUIBK6o6FWUwUKuDV2Jiv15Zk0OKsUG4By/HmTbiWpXcZiH9BqhvAoumEU74NEf0eVelTGDnXhbGieJ7Ln2IPXIr7JDYtNi723OL+R2S3e/4SwKLJp+wd0yomum7dOt+7OxblzTGrhcfpLCUk+/UAvnRAIFayZDpiWDIRCQtcSiumikuzSTX6DtHAvZLCMuY2TMzDZFc8SvAHF2hjybs+HlPbsZO7vXFzQq6D2BI+mY9uXdrltLDs3s2lM6htDF4YwxzhgBCfdYkAAVpEXqjkxZ5wRdXW7glp4E+g98QnpUrbsRxvIvc2rnPr4TCwjd0izytA8AQBIV31nyq3xMXdlnpKNKBwyMiYYO2bY9yF8Qd7aFB25TThNeC6IchDBITWGSlWukngqjUljsNsmwB47qXM2cQHbhQyMgaDxHqxwwC4YwG2v+Ii5JTe02hl2vw5lQILwYdU28b5NevOXTWbyLjeNYxOaKv3+peiN+n0DwxEZSCeQkbi/TLp2DMyej+dVFS1SuPPeASPHx/8iVrAwuSI7ld/MlkaEWjeXiL1YEFBKbIE1j0fF8dyLc=
  api_key:
    secure: TIc1RHwQKlUxaXUoHDTX6vodCZ0qRbCdlBU8Z305Ot5RV79W4g5xrTfubqf5AnA40wRbXKPLctnmHhi+ArbdFfZ4Cz6W43YdqYfeo+jmdkfvnSV5N1qTuw3YoxWGwMUKK00kBmO/z6U70aV+T8H8gwZHV0EgaAEFPxVlxHG1dP0S/7BKuzgLVQpnyLhe5Lw/DTEvFTKEnxUuTl15Ja47OJD9vitNm61MfSgkz83x1i0B9lISG9lfAf4/D+obcVNRKQCSuyWB2Z7f9BvE3hXSuR82XllPdMRsn37wKRqUJLgf3nz/fgHtuGgnpllC7sx9wT951oTXUeJC5JDcm7q0sTZIgpb15Q9muxbdJCjMVGsh7oEjOJw6lYpXYzAb2hMyIBEfT4ngrMfkPM5ThAqiFzQjotVjph7cPozFv0Kfq2Rjw4I//F48jScSuH2uC5wTXoJv8mWF9EWkzbyiGEhR92ZxT1GntLScYB3Fx4qTGA+rmuqi9RFdCFFtTYOaYvS/RB4pmRuLIJs776a/r0Xmg7LJup1KSVJhlK9PfJJt7Faqis7p0CehvZXb/xOhN8YcJIETr0AGccMobQtnBjZ5b0UySEgT1RVwXsUcxIKUKxKENlvy+3VT1MBih4Ey6M/BRDjJm+Bk+U19CWLkoJyyERShWnw3Vs71uyoEJtn643w=
  on:
    branch: master
    repo: groundbreaker/qewl
